name: Deploy Dnd-todo App

on: push
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Get a repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Test app start
        run: npm run start
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get a repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Lint App
        run: npm run lint:check
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get a repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build App
        run: npm run build
