name: Deploy DnD-todo App

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get a repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test app build
        run: npm run start
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get a repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint App
        run: npm run test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get a repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build App
        run: npm run build
